#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
# anaconda
export PATH=/opt/anaconda/bin:$PATH
# local bin
export PATH=/home/shaurya/.local/bin:$PATH
export PATH=/home/shaurya/.npm/node_modules/bin/:$PATH
export PATH=/home/shaurya/.ghcup/bin:$PATH
export PATH=/home/shaurya/.emacs.d/bin:$PATH
export PATH=/home/shaurya/go/bin:$PATH
export PATH=/home/shaurya/.cabal/bin/:$PATH
#export PATH=/home/shaurya/.xmonad:$PATH

if [ -e /home/shaurya/.nix-profile/etc/profile.d/nix.sh ]; then . /home/shaurya/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
