#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com> 

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# dotfiles
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
# list directories
alias lsd='ls -d */'
# Customize to your needs...
alias sudo='sudo -E '
# using neovim
alias vi=nvim
alias vim=nvim
# lazygit
alias lg=lazygit
# Juspay
alias run-nau='stack exec nau-exe -- convert --input ../euler-ps-nau/Backend/src/ --outputDir ../euler-gen/src/ --useUndefined --maxThreads 8'
#default editor
export VISUAL='nvim'
export EDITOR='nvim'
#python virtual env
export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=~/Code
# go
export GOPATH=~/go
#source /usr/bin/virtualenvwrapper.sh

# source /usr/share/nvm/init-nvm.sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This sets up nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # nvm bash_completion

# opam configuration
test -r /home/shaurya/.opam/opam-init/init.zsh && . /home/shaurya/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh

export ANDROID_SDK_ROOT=/opt/android-sdk/platforms/android-29 
export ANDROID_SDK=/opt/android-sdk/
export gtime=time

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
